### ISSUE TITLE
v2.0.0 is based on 2.4.2 of spring-cloud-aws

### ISSUE THREAD

**Issue by smilasek** [idealo/spring-cloud-stream-binder-sqs#122]
The new upgraded version is based on [spring-cloud-aws:2.4.2 ](https://github.com/idealo/spring-cloud-stream-binder-sqs/blob/main/pom.xml#L50), so imported dependencies use spring 2.X.X classes under the hood. 

Before announcing an update to Spring v3, you should update all required dependencies and wait for v.3.0.0 of this library. 
For a time being [v.3.0.0-M3](https://github.com/awspring/spring-cloud-aws/releases/tag/v3.0.0-M3) has been released

Additionally SPring Boot 3 requires minimum Java 17 version, so maybe it would be good to update compiler options as well?

**Comment by smilasek** [comment]
Hey, any progress here?

https://github.com/awspring/spring-cloud-aws/releases/tag/v3.0.0 has been released recently, so I could assume that you could bump it up and adjust the code.

**Comment by hendrik-nibbrig-idealo** [comment]
Hey there. Unfortunately there is no priority on this but I hope we will be able to sneak it in between. Otherwise feel free to create a PR

**Comment by smilasek** [comment]
Closing as it was solved in v3
