### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by benkeil** [idealo/spring-cloud-stream-binder-sqs#35]
How to scale an application? It looks like the concurrency settings are ignored and we can process only 10 messages.
Do you have example how you are using spring cloud stream in your environment?

**Comment by benkeil** [comment]
You could also take a look at e.g. the kafka-streams binder and check what they are doing.

**Comment by mKeRix** [comment]
The Kafka Streams binder is a relatively special case, but the regular Kafka binder actually has a nice implementation for this that I think might work here as well. I'll give this a shot and report back!

**Comment by mKeRix** [comment]
Unfortunately other projects kept me busy the last weeks, but I submitted a draft pull request with support for the concurrency setting just now. There are still a few open points that I'd like to discuss with my team before this can go live. Just so you know that there is progress. :)
